version: '2'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    volumes:
      - ./pg/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DATABASE: letters
      POSTGRES_USER: letters
      POSTGRES_PASSWORD: letters
    expose:
      - "5432"
    ports:
      - "5432:5432"
  python:
    build:
      context: .
      dockerfile: Dockerfile-python
    env_file:
      - .env
    depends_on:
      - postgres
    links:
      - postgres:postgres
